export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_END = 'REGISTER_END';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const ADD_PROJECTS_START = 'ADD_PROJECTS_START';
export const ADD_PROJECTS_SUCCESS = 'ADD_PROJECTS_SUCCESS';
export const ADD_PROJECTS_END = 'ADD_PROJECTS_END';
export const ADD_PROJECTS_FAIL = 'ADD_PROJECTS_FAIL';

export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL';

export const ADD_SPRINTS_START = 'ADD_SPRINTS_START';
export const ADD_SPRINTS_SUCCESS = 'ADD_SPRINTS_SUCCESS';
export const ADD_SPRINTS_END = 'ADD_SPRINTS_END';
export const ADD_SPRINTS_FAIL = 'ADD_SPRINTS_FAIL';

export const FETCH_SPRINTS_START = 'FETCH_SPRINTS_START';
export const FETCH_SPRINTS_SUCCESS = 'FETCH_SPRINTS_SUCCESS';
export const FETCH_SPRINTS_FAIL = 'FETCH_SPRINTS_FAIL';

export const ADD_TASKS_START = 'ADD_TASKS_START';
export const ADD_TASKS_SUCCESS = 'ADD_TASKS_SUCCESS';
export const ADD_TASKS_END = 'ADD_TASKS_END';
export const ADD_TASKS_FAIL = 'ADD_TASKS_FAIL';

export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';
